version: '2'
services:
  postgresql12:
    image: 'bitnami/postgresql:13'
    ports:
      - '5432:5432'
    volumes:
      - 'postgresql_data:/bitnami/postgresql'
    environment:
      - POSTGRESQL_USERNAME=user
      - POSTGRESQL_PASSWORD=password
      - POSTGRESQL_DATABASE=db
      - ALLOW_EMPTY_PASSWORD=yes
volumes:
  postgresql_data:
    driver: local